# Site settings
title: "علی‌رضا حیاتی"
motto: "نوشته‌های علی‌رضا به زبان پارسی"
author: Alireza Hayati
email: alirezahayati@outlook.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mehdix.ir" # the base hostname & protocol for your site
keywords: "پارسی، یادداشت، نبشته، رایانه، برنامه‌نویسی"
copyright: "Uncopyrighted."
robot: ""
description: > # this means to ignore newlines until "baseurl:"
  یادداشت‌های علی‌رضا حیاتی به زبان پارسی.

long_description: >
  در تلاش برای ساخت دنیایی بهتر با فناوری، و آرامش.

twitter_username: alrrza
github_username:  farsinevesht
fullname: "علی‌رضا حیاتی"
favicon: "assets/img/favicon.png"


#outputting
permalink: :title.html

# Build settings
markdown: Markright
kramdown:
    coderay_line_numbers: nil
encoding: utf-8
timezone: Europe/Berlin

paginate: 5
paginate_path: "/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "علی‌رضا حیاتی"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "علی‌رضا حیاتی"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

gems:
  - jekyll-sitemap
  - jalalidate
  - coderay
  - jekyll-paginate

collections:
  projects:
    output: true
